import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// app/layout.tsx (または pages/_app.tsx)
import { PresenceProvider } from "@/context/PresenceContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <PresenceProvider>{children}</PresenceProvider>
      </body>
    </html>
  );
}
