services:
  satopon_backend:
    build: ./backend/
    container_name: satopon_backend
    working_dir: /app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - satopon_mongo
      - satopon_redis

  satopon_mongo:
    image: mongo:8.0.10
    container_name: satopon_mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - satopon_mongo_data:/data/db

  satopon_redis:
    image: redis:8.0
    container_name: satopon_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - satopon_redis_data:/data

  satopon_frontend:
    build: ./frontend/
    container_name: satopon_frontend
    working_dir: /app
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    tty: true
    command: ["npm", "run", "dev", "--", "-p", "3002"]

  satopon_nginx:
    image: nginx:1.28.0
    container_name: satopon_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - satopon_frontend
      - satopon_backend

volumes:
  satopon_mongo_data:
  satopon_redis_data:
